# Generated by Django 2.2 on 2021-01-27 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('dob', models.DateTimeField()),
                ('PhoneNumber', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('ssn', models.CharField(max_length=30)),
                ('page1', models.FileField(upload_to='DriversLicense/%Y/%m/%d')),
                ('page2', models.FileField(upload_to='DriversLicense/%Y/%m/%d')),
                ('UtilityBill', models.FileField(upload_to='utility/%Y/%m/%d')),
            ],
        ),
    ]
