# Generated by Django 2.2 on 2021-01-27 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tedhair', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='userdetails',
            new_name='UserDetailModel',
        ),
    ]
